# version: "3.3"

services:
  breedbase_zh:
    image: imagebreed/imagebreed:10.1
    restart: always
    depends_on:
      - breedbase_db_zh
      - flask
    container_name: breedbase_web_zh
    ports:
      - 5080:8080
      - 23:25
    networks:
      - app-network
    environment:
      - PGPASSFILE=/home/production/.pgpass
    #  - MODE=DEVELOPMENT
    #  - RUN_DB_ONTOLOGY_SGNSTAT_UPDATES=TRUE
    #  - RUN_DB_ONTOLOGY_ISOL_UPDATES=TRUE
    #  - RUN_DB_ONTOLOGY_G2F_UPDATES=TRUE
    #  - RUN_DB_ONTOLOGY_ALF_UPDATES=TRUE
    #  - RUN_DB_PATCHES=TRUE
      - DATABASE_HOST=breedbase_db_zh
    #  - DATABASE_NAME=empty_fixture
    #  - DATABASE_USER=postgres
    #  - DATABASE_PASSWORD=postgres
    #  - DATABASE_OPERATOR=janedoe
    #volumes:
    #  - type: bind
    #    source: ./development/sgn_local_docker.conf
    #    target: /home/production/cxgn/sgn/sgn_local.conf
    #  - type: bind
    #    source: ${HOME}/nickmorales/imagebreed
    #    target: /home/production/cxgn/sgn
    #  - type: bind
    #    source: ${HOME}/cxgn/DroneImageScripts
    #    target: /home/production/cxgn/DroneImageScripts
    #  - type: bind
    #    source: ${HOME}/nickmorales/imagesol
    #    target: /home/production/cxgn/imagesol
    #  - type: bind
    #    source: ${HOME}/cxgn/R_libs
    #    target: /home/production/cxgn/R_libs
    #  - type: bind
    #    source: ${HOME}/cxgn/perl-local-lib
    #    target: /home/production/cxgn/local-lib
    #  - type: bind
    #    source: ${HOME}/archive
    #    target: /home/production/archive
    #  - type: bind
    #    source: ${HOME}/tmp
    #    target: /home/production/tmp
    #  - type: bind
    #    source: ${HOME}/cache
    #    target: /home/production/cache
    #  - type: bind
    #    source: ${HOME}/cluster
    #    target: /home/production/cluster
    #  - type: bind
    #    source: ${HOME}/blast
    #    target: /home/production/blast
    #  - type: bind
    #    source: ${HOME}/images
    #    target: /home/production/public/images
    # FOLLOWING ARE IMPORTANT FOR RUNNING OPENDRONEMAP
    #  - type: bind
    #    source: /var/run/docker.sock
    #    target: /var/run/docker.sock
  breedbase_db_zh:
    image: imagebreed/imagebreedpg:10.1
    restart: always
    container_name: breedbase_db_zh
    networks:
      - app-network
    #volumes:
    #  - type: bind
    #    source: ${HOME}/pgdata
    #    target: /var/lib/postgresql/data
  flask:
    build: 
      context: flask_dev
      dockerfile: Dockerfile
    container_name: flask
    # expose:
      # - "4000"
    env_file:
      - "flask_dev/.env"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
  
  imagebreed-nginx:
    container_name: imagebreed-nginx
    image: nginx
    ports:
      - "70:70"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - flask
      - breedbase_zh
    networks:
      - app-network

networks:
  app-network:
    driver: bridge