events { worker_connections 1024; }

http {
    server {
        listen 70;

        # 1. Route frontend requests to the Perl container
        location / {
            allow 140.112.0.0/24;
            allow 127.0.0.1;
            allow 172.23.0.0/24;
            deny  all;
            proxy_pass http://breedbase_zh:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header User-Agent $http_user_agent;
        }

        # 2. Route API requests to the Flask container
        location /api/ {
            allow 140.112.0.0/16;
            allow 172.23.0.0/24;
            allow 127.0.0.1;
            deny  all;
            proxy_pass http://flask:4000/; # Note the trailing slash
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}